name: "Notify on failure"
description: "Send a message to Slack when a job fails"
inputs:
  SLACL_BOT_TOKEN:
    description: "slack bot token passed through from secrets."
    required: true
  SLACK_CHANNEL_ID:
    description: "slack channel ID to send messages to (find by right clicking on channel -> view channel details -> about)."
    required: true
runs:
  using: "composite"
  steps:
    - name: Get commit or title and url
      ## Full commit message (title and body) create an invalid JSON payload
      run: |
        echo "commit_title=$(git show -s --format=%s)" | tr -d '\t"\' >> "$GITHUB_ENV"
        echo "commit_sha=$(git show -s --format=%H)" >> "$GITHUB_ENV"
      shell: bash
    - name: Send failure to Slack
      id: slack
      uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 #v3.0.1
      with:
        method: chat.postMessage
        token: ${{ inputs.SLACK_BOT_TOKEN }}
        payload: |
          {
            "channel": "${{ inputs.SLACK_CHANNEL_ID }}",
            "text": "<!here> <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.job }}> run failed for \"<${{ format('{0}/{1}/commit/{2}', github.server_url, github.repository, env.commit_sha) }}|${{ env.commit_title }}>\" on <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.repository }}> :fire:",
            "attachments": [
              {
                "color": "#ff0000",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Workflow*: ${{ github.workflow }}\n*Failed job*: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.job }}>\n*Commit:* <${{ format('{0}/{1}/commit/{2}', github.server_url, github.repository, env.commit_sha) }}|${{ env.commit_title }}>\n*Branch:* ${{ github.ref }}\n*Author:* ${{ github.triggering_actor }}"
                    }
                  }
                ]
              }
            ]
          }
