name: "Notify on failure"
description: "Send a message to Slack when a job fails"
inputs:
  SLACK_WEBHOOK_URL:
    description: "url that tells Slack which channel should receive this notification."
    required: true
runs:
  using: "composite"
  steps:
    - name: Get commit title and url
      ## Full commit message (title and body) create an invalid JSON payload
      run: |
        echo "commit_title=$(git show -s --format=%s)" >> "$GITHUB_ENV"
        echo "commit_sha=$(git show -s --format=%H)" >> "$GITHUB_ENV"
      shell: bash
    - name: Send failure to Slack
      # Third-party action, pin to commit SHA!
      # See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
      uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        payload: |
          {
            "text": "<!here> <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.job }}> run failed for \"<${{ github.event.pull_request.html_url || format('{0}/{1}/commit/{2}', github.server_url, github.repository, env.commit_sha) }}|${{ github.event.pull_request.title || env.commit_title }}>\" on <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.repository }}> :fire:",
            "attachments": [
              {
                "color": "#ff0000",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Workflow*: ${{ github.workflow }}\n*Failed job*: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.job }}>\n*Commit or PR:* <${{ github.event.pull_request.html_url || format('{0}/{1}/commit/{2}', github.server_url, github.repository, env.commit_sha) }}|${{ github.event.pull_request.title || env.commit_title }}>\n*Branch:* ${{ github.ref }}\n*Author:* ${{ github.triggering_actor }}"
                    }
                  }
                ]
              }
            ]
          }
