name: Tests notify GHA
on: workflow_dispatch

jobs:
  send_message_test_channel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      - name: Failing on purpose
        run: exit 1
      - name: Send failure to Slack
        uses: ./
        if: ${{ failure() }}
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
